/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DeleteNoteButton: typeof import('./components/DeleteNoteButton.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    LogoutButton: typeof import('./components/LogoutButton.vue')['default']
    NewNotaForm: typeof import('./components/NewNotaForm.vue')['default']
    RegisterForm: typeof import('./components/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateNotaForm: typeof import('./components/UpdateNotaForm.vue')['default']
  }
}
